steps:
  - name: 'gcr.io/cloud-builders/gcloud'  # Use the official gcloud builder image
    id: Pre-build steps
    entrypoint: /bin/bash
    args: 
      - -c
      - |
        gcloud compute os-login describe-profile
        for i in $(gcloud compute os-login ssh-keys list); do echo $i; gcloud compute os-login ssh-keys remove --key $i; done #TBD update the logic to run deletion keys if no of keys >2
        echo "All previous Keys deleted from Cloudbuild's profile"
        
        echo " Creating build-id folder with commit-id=$COMMIT_SHA and build-id=$BUILD_ID and revison_id=$REVISION_ID"
        gcloud compute ssh ftwomicroinstance --zone=asia-south1-a --project jmc-devsecops --command ' mkdir -m 777 deploymentscripts/$BUILD_ID && ls '  --tunnel-through-iap --force-key-file-overwrite --strict-host-key-checking=no
  - name: 'gcr.io/cloud-builders/gcloud'  # Use the official gcloud builder image
    entrypoint: /bin/bash
    args: 
      - -c
      - |
        gcloud compute scp --recurse /workspace ftwomicroinstance:~/deploymentscripts/$BUILD_ID --zone=asia-south1-a --tunnel-through-iap --force-key-file-overwrite --strict-host-key-checking=no
        gcloud compute ssh ftwomicroinstance --zone=asia-south1-a --project jmc-devsecops --command 'cd deploymentscripts/$BUILD_ID/workspace/ && pwd && ls'  --tunnel-through-iap --force-key-file-overwrite --strict-host-key-checking=no
  

  #- name: 'gcr.io/cloud-builders/docker'
 #   args: ["build", "-t", "gcr.io/kubernetes-amit-test/github.com/0xvoila/apache/phoenix:$SHORT_SHA", "."]

 # - name: "gcr.io/cloud-builders/docker"
#    args: ["push", "gcr.io/kubernetes-amit-test/github.com/0xvoila/apache/phoenix:$SHORT_SHA"]

 # - name: "alpine/helm:latest".   --- It is not working 
#    args: ["helm","upgrade","mychart","image", "gcr.io/kubernetes-amit-test/github.com/0xvoila/apache/phoenix:$SHORT_SHA"]




