steps:
  - name: 'gcr.io/cloud-builders/gcloud'  # Use the official gcloud builder image
    entrypoint: '/bin/bash'
    args: 
      - '-c'
      - |
        gcloud compute scp --recurse ./ ftwomicroinstance:~/deploymentscripts/hello-world/ \
         --zone=asia-south1-a \
         --tunnel-through-iap

